### ISSUE TITLE
Prepare the demonstration for the usage of bridge

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/ros2-web-bridge#103]
We would like to add a demonstration to show the usage of current bridge based on ROS 2.0.

**Comment by qiuzhong** [comment]
So what're the outputs for this feature? 

The following items come to my mind now:
* JavaScript code snippet based on the rosbridge v2 protocol operations.
* README for all these examples

Any good suggestion?

**Comment by minggangw** [comment]
I suggest we can submit our demonstration which is prepared for ROSCon2018 to this repo, so every user from beginner to veteran can have a blueprint what this module can offer and do.

**Comment by qiuzhong** [comment]
Got it.

**Comment by minggangw** [comment]
I think we can mark this issue as **done** now, I am going to close it.
