### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by ErijBNT** [RobotWebTools/ros2-web-bridge#120]
I am  always getting this error while running npm install 
![Screenshot from 2019-05-29 04-13-35](https://user-images.githubusercontent.com/27079391/58526832-4d30d900-81c8-11e9-9aeb-9f32bf4a4372.png)

**Comment by minggangw** [comment]
The latest version of ros2-web-bridge ([v0.2.7](https://www.npmjs.com/package/ros2-web-bridge/v/0.2.7)) has been released, which was verified on [travis-ci](https://travis-ci.org/RobotWebTools/ros2-web-bridge/builds/570655926?utm_source=github_status&utm_medium=notification) with [dashing patch release2](https://github.com/ros2/ros2/releases/tag/release-dashing-20190806). You can reference the configuration of the CI to setup your own env, thanks!

**Comment by minggangw** [comment]
I think it doesn't happen any more, so let's close it.
