### ISSUE TITLE
run the ros bridge error

### ISSUE THREAD

**Issue by ErijBNT** [RobotWebTools/ros2-web-bridge#121]
![Screenshot from 2019-05-29 04-26-08](https://user-images.githubusercontent.com/27079391/58527272-ef04f580-81c9-11e9-8bb1-bcfff43a437c.png)

**Comment by mschlafly** [comment]
I am having this problem too. Did you ever find a solution?

**Comment by minggangw** [comment]
The latest version of ros2-web-bridge ([v0.2.7](https://www.npmjs.com/package/ros2-web-bridge/v/0.2.7)) has been released, which was verified on [travis-ci](https://travis-ci.org/RobotWebTools/ros2-web-bridge/builds/570655926?utm_source=github_status&utm_medium=notification) with [dashing patch release2](https://github.com/ros2/ros2/releases/tag/release-dashing-20190806). You can reference the configuration of the CI to setup your own env, thanks!

**Comment by minggangw** [comment]
I think it doesn't happen any more, so let's close it.

**Comment by maozaizhou** [comment]
> I think it doesn't happen any more, so let's close it.

hello, I came into the same problem, and can't figured out why

**Comment by minggangw** [comment]
Please make sure rclnodejs.node is generated.

**Comment by mikelyndersOKCC** [comment]
Hello, I am having a similar problem. 

The bindings I appear to be missing are for a package called  **int64-napi**
The following error occurs when running rosbridge.js:

>/home/pi/dev_ws/src/ros2-web-bridge/node_modules/bindings/bindings.js:135
  throw err;
  ^
>
>Error: Could not locate the bindings file. Tried:
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/build/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/build/Debug/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/build/Release/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/out/Debug/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/Debug/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/out/Release/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/Release/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/build/default/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/compiled/10.19.0/linux/arm/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/addon-build/release/install-root/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/addon-build/debug/install-root/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/addon-build/default/install-root/int64.node
 → /home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/lib/binding/node-v64-linux-arm/int64.node
    at bindings (/home/pi/dev_ws/src/ros2-web-bridge/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/pi/dev_ws/src/ros2-web-bridge/node_modules/int64-napi/index.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/dev_ws/src/ros2-web-bridge/node_modules/rclnodejs/lib/duration.js:18:15)


ROS : eloquent
npm : v6.13.4
node : v10.19



## Solved

Running ```node-gyp rebuild``` in node_modules/int64-napi generated the .node file and solved the problem.

I'm not sure why the .node bindings weren't generated when I ran `npm install`.

**Comment by minggangw** [comment]
I haven't met this before also, anyway it was solved :smile:
