### ISSUE TITLE
您好，王先生，我遇到了安装错误的问题，请您帮助解决！谢谢！

### ISSUE THREAD

**Issue by ZuumaCoder** [RobotWebTools/ros2-web-bridge#123]
![image](https://user-images.githubusercontent.com/27922947/61367777-ed4cd980-a8be-11e9-9428-3531566a9783.png)

**Comment by minggangw** [comment]
Please try without _sudo_

**Comment by minggangw** [comment]
The latest version of ros2-web-bridge ([v0.2.7](https://www.npmjs.com/package/ros2-web-bridge/v/0.2.7)) has been released, which was verified on [travis-ci](https://travis-ci.org/RobotWebTools/ros2-web-bridge/builds/570655926?utm_source=github_status&utm_medium=notification) with [dashing patch release2](https://github.com/ros2/ros2/releases/tag/release-dashing-20190806). You can reference the configuration of the CI to setup your own env, thanks!

**Comment by minggangw** [comment]
I think it doesn't happen any more, so let's close it.
