### ISSUE TITLE
Ros2 Launch file 

### ISSUE THREAD

**Issue by M-Redel** [RobotWebTools/ros2-web-bridge#147]
Is it possible to start the package via the ros2 launchfile.py?

**Comment by minggangw** [comment]
Currently, this module, ros2-web-bridge, has not been integrated with [ros2cli](https://github.com/ros2/ros2cli)  if that's what you want to have.

**Comment by mis-eu** [comment]
would be great to have the feature of launching with ros2 launchfile.py on 20.04/Foxy

**Comment by minggangw** [comment]
We need to change ros2cli to support this feature, so we don't further plan right now.

**Comment by spygibas** [comment]
I think you can do via msg std_msgs/msg for make execute a launch/kill files example on these link below but you need to update that code for support some package for ros2 
https://answers.ros.org/question/268044/can-i-execute-a-launch-file-or-run-a-node-through-roswebtool/
