### ISSUE TITLE
Connection fail with browser from external PC

### ISSUE THREAD

**Issue by botamochi6277** [RobotWebTools/ros2-web-bridge#154]
I have connection error to publish from browser.

I logged in  my ros pc (raspberry pi 4 installed foxy) with ssh and executed following command.

Terminal 1:
```
node bin/rosbridge.js
```

Terminal2:
```
cd examples && node index.js
```

When I opened `http://foxy.local:3000/html/publisher.html` from my host PC, the following page appeared. `foxy` is hostname of the raspberrypi.

<img width="1383" alt="ScreenShot 2020-09-26 17 18 23" src="https://user-images.githubusercontent.com/14128408/94337224-df96f600-0023-11eb-89d0-dc4486458b73.png">

Google Chrome said "WebSocket connection to 'ws://localhost:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Ros.connect @ roslib.js:2224
(anonymous) @ publisher.html:39".
<img width="279" alt="ScreenShot 2020-09-26 17 37 47" src="https://user-images.githubusercontent.com/14128408/94337382-f1c56400-0024-11eb-8cae-132758f47a81.png">

**Comment by minggangw** [comment]
Please try to change the address of ws server to your actual one, I think it should be the address of `raspberry pi 4`

https://github.com/RobotWebTools/ros2-web-bridge/blob/248f2ee44c525ebbd7c90e7c056ba62f3939eb02/examples/html/publisher.html#L39

This simple demo is designed to run the bridge and the web browser on the same machine.

**Comment by botamochi6277** [comment]
Thank you for replying.
I succeed to publish when i run the bridge and the web browser on the same raspberry pi.
I fail to do, although, when i run the web browser on another pc with actual address (192.168.4.2).

**Comment by minggangw** [comment]
> I fail to do, although, when i run the web browser on another pc with actual address (192.168.4.2).

What's the error log? still `net::ERR_CONNECTION_REFUSED`?

I suggest you could create a `WebSocket ` and try to connect to the address of raspberry pi, thus we could make sure it's reachable. Also, please run the bridge `DEBUG=ros2-web-bridge* node bin/rosbridge.js` to enable debug output and get more useful information.

**Comment by botamochi6277** [comment]
I **succeed to publish** topics with the web browser from my Mac (external PC).
I edit line 40 in `examples/html/publisher.html` as below, 
`ros.connect('ws://localhost:9090');` -> `ros.connect('ws://foxy.local:9090');`.
`foxy` is hostname of my rospc running ros2-web-bridge.

Mac may try to connect 'ws://localhost:9090' as `'ws://[mac ip address]:9090'`.

**Comment by minggangw** [comment]
Great! So could we close this issue now?

**Comment by botamochi6277** [comment]
Yes, Please.

**Comment by minggangw** [comment]
Close this issue, please feel free to reopen it if you still have problems, thanks!
