### ISSUE TITLE
Bug ROS2 custom message in subfolder

### ISSUE THREAD

**Issue by sirawats** [RobotWebTools/ros2-web-bridge#175]
**My custom msg directory**
```
|--oru_msgs
|  |--msg
|     |--bunker_base
|        |--BunkerMototState.msg
```
then `npm install`
so rclnodejs generated the ros2 msg js interface
```
|--ros2-web-bridge/node_modules/rclnodejs/
|  |--generated
|     |--oru_msgs
|        |--oru_msgs__bunker_base__BunkerMotorState.js 
```
**The result:**
![Screenshot from 2021-02-05 17-08-22-x](https://user-images.githubusercontent.com/21076861/107023874-cffd9a00-67d9-11eb-8ad2-33ca4284abe6.png)

### **According to my investigation, I had 2 methods to solve this**
**1. Change my `oru_msgs` directory structure (remove bunker_base/ )**
```
|--oru_msgs
|  |--msg
|     |--BunkerMototState.msg
```
then `npm install`, so rclnodejs/generation is going to be
```
|--ros2-web-bridge/node_modules/rclnodejs/
|  |--generated
|     |--oru_msgs
|        |--oru_msgs__msg__BunkerMotorState.js 
```

_but this gonna be force user to can't have subfolder and inflexible!_

**2. Manually edit `rclnodejs/generated`** without change directory structure
```
|--ros2-web-bridge/node_modules/rclnodejs/
|  |--generated
|     |--oru_msgs
|        |--oru_msgs__bunker_base__BunkerStatus.js  ---> oru_msgs__msg__BunkerMotorState.js
```
and edit _line: 101_ of `oru_msgs__msg__BunkerMotorState.js` 
from `return {pkgName: 'oru_msgs', subFolder: 'bunker_base', interfaceName: 'BunkerMotorState'};`
to `return {pkgName: 'oru_msgs', subFolder: 'msg', interfaceName: 'BunkerMotorState'};`

**The result:**
![Screenshot from 2021-02-05 17-13-19-x](https://user-images.githubusercontent.com/21076861/107023880-d25ff400-67d9-11eb-82cf-53efb42ba726.png)

So I think this should be improved

**Comment by debanik123** [comment]
source your catkin_ws with your custom msg
