### ISSUE TITLE
Status message response should be sent back to clients for every message

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#26]
This project implemented the  [rosbridge v2 protocol](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/ROSBRIDGE_PROTOCOL.md)
Generally, sending an rosbridge message to the bridge should always return a response no matter the message is handled well.

However, this is not the cases, web socket client cannot receive response from the bridge web socket server:

```
const webSocket = require('ws');
const ws = new webSocket('ws://localhost:9090');

ws.on('open', function open() {
  ws.send('{"op": "advertise", ... }');
});

ws.on('message', function incoming() {
  // never enter
});
```

To make the rosbridge v2 protocol testing easier, please implement this feature.

**Comment by qiuzhong** [comment]
This is also the experimental feature in [3.2 section of rosbridge v2 protocol](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/ROSBRIDGE_PROTOCOL.md#32-status-messages)

**Comment by minggangw** [comment]
Thanks for the finding, I will take this issue.

**Comment by qiuzhong** [comment]
Verified. Basically valid operations can receive responses now.
