### ISSUE TITLE
Add command line wrapper and argument processor

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/ros2-web-bridge#3]
Add command line wrapper so that user can run a specific script instead of running `node index.js` command

Add argument processor that is compatible with 1.0 bridge, e.g. `--port`, `--address`, `--retry_startup_delay`, `--fragment_timeout` and etc.

**Comment by kenny-y** [comment]
Started to work on this one.

**Comment by minggangw** [comment]
https://github.com/RobotWebTools/ros2-web-bridge/commit/d77c77b18ea49011b3cb52569a7bc12668f938e4 has landed, so close this issue.
