### ISSUE TITLE
rosbridge v2 protocol specification: advertise

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#36]
According to the [rosbridge v2 protocol specification 3.4.1  Advertise ( advertise )](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/ROSBRIDGE_PROTOCOL.md#341-advertise--advertise-)

> If the topic already exists with a different type, an error status message is sent and this message is dropped.

```
// 1st message
Message: '{"op": "advertise", "id": "create_topic1", "topic": "example_topic", "type": "std_msgs/String"}'
Expected: success
Actual response: '{"op": "set_level", "level": "none"}'

// 2nd message
Message: '{"op": "advertise", "id": "create_topic2", "topic": "example_topic", "type": "std_msgs/Char"}'
Expected: error as same topic already exists but with different type
Actual response: '{"op": "set_level", "level": "none"}'
```

**Comment by minggangw** [comment]
I will check this situation to see if it's supported by ROS2 now.

**Comment by qiuzhong** [comment]
Tried with PR42. Same as PR43, one more normal response is sent back to the client.

**Comment by qiuzhong** [comment]
Verified. No more the extra response any more.
