### ISSUE TITLE
Invalid topic type for unadvertise operation should return error not warning

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#46]
For `advertise` operation, invalid topic will cause an error status response as an TypeError is caught during the `executeCommand`. However, invalid topic type for `unadvertise` operation will return a warning status response, like this:

```
    this._registerOpMap('unadvertise', (command) => {
      if (!this._topicsPublished.has(command.topic)) {
        debug(`The topic ${command.topic} does not exist.`);
        let error = new Error();
        error.level = 'warning';
        throw error;
      }
      debug(`unadvertise a topic: ${command.topic}`);
      this._topicsPublished.delete(command.topic);
      this._resourceProvider.destroyPublisher(command.topic);
    });
```
Since the topic is not in `_topicPublished`, it simply returns a warning status response. This is logic of another rule indicated in the spec while the topic type is valid.

Well, the specification doesn't indicate this explicitly but I think it should keep aligned with the `advertise` operation.

**Comment by minggangw** [comment]
We should distinguish these two cases:
- invalid topic
- doesn't exist topic

With different level of errors, I will investigate this issue.

**Comment by qiuzhong** [comment]
Verified. This issue is fixed.
