### ISSUE TITLE
Add Status feature [experimental]

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/ros2-web-bridge#5]
> - op: `set_level` - one of 'info', 'warning', 'error', or 'none'
> - op: `status` - status message [experimental]

**Comment by minggangw** [comment]
I think we have implemented this feature already, please @qiuzhong confirm it, thanks!

**Comment by qiuzhong** [comment]
@minggangw ,  `set_level` has been implemented but I didn't see there is any `status` operation branch in the code.

**Comment by minggangw** [comment]
Oh, I misunderstood the `op` here. We only implemented the `set_level`, so let's just mark the `set_level` as **DONE**.
