### ISSUE TITLE
Bridge server process signal handler

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#52]
The bridge server sometimes cannot response `CTRL + C` well.

When the bridge server is running, it will initialize the `rclnodejs`, which can catch the `SIGINT` signal. So the `rclnodejs` loop might exit but the web socket server might not exit.

**Comment by minggangw** [comment]
Thanks for the funding, I will take this issue.

**Comment by qiuzhong** [comment]
Verified. #53 make sure the web socket server is closed when the process is exiting.
