### ISSUE TITLE
Bridge server crashed when running a websocket client

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#58]
I got bridge server crashes when a web socket client running for the second time. Here is the crash traceback information:

```
$ node bin/rosbridge.js 
The web socket server started on ws://localhost:9090
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [node]
 2: 0x121a2cc [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: node::TCPWrap::Instantiate(node::Environment*, node::AsyncWrap*) [node]
 5: node::ConnectionWrap<node::TCPWrap, uv_tcp_s>::OnConnection(uv_stream_s*, int) [node]
 6: 0x144a930 [node]
 7: 0x144ffa8 [node]
 8: uv_run [node]
 9: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [node]
10: node::Start(int, char**) [node]
11: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
12: 0x8aee41 [node]
Aborted (core dumped)

```
A core dump file was generated but its size is too big to attach to here. I can provide it in other way.
Here is my websocket client code:

```
const WebSocket = require('ws');

const ws = new WebSocket('ws://localhost:9090');
var count = 0;
ws.on('open', function open() {
  const msg = {
    "op": "subscribe",
    "id": "subscribe_id1",
    "topic": "example_topic",
    "type": "std_msgs/String"
  };
  ws.send(JSON.stringify(msg));
  count++;
});

ws.on('message', function incoming(data) {

  console.log(`${count}:` + data.toString());
  if (count === 4) {
    console.log('about to close ws');
    ws.close();
    count++;
  }

  if (count === 3) { 
    count++;
  }

  if (count === 2) {
    const msg2 = {
      op: 'publish', id: 'publish_id1', topic: 'example_topic', msg: {data: 'hello world!'}
    };
    ws.send(JSON.stringify(msg2));
    count++;
  }

  if (count === 1) {
    const msg1 = {
      op: 'advertise', id: 'advertise_id1', topic: 'example_topic', type: 'std_msgs/String'      
    };
    ws.send(JSON.stringify(msg1));
    count++;
  }
});

```

# Reproduce steps:
``
$ node client.js
1:{"op":"set_level","level":"none"}
2:{"op":"set_level","level":"none"}
3:{"op":"set_level","level":"none"}
4:{"op":"publish","topic":"example_topic","msg":{"data":"hello world!"}}
about to close ws

$ node client.js 
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)

``

## Environments:
* Node.js v8.9.4
* ros2-linux: [ROS2 package from Linux CI](http://ci.ros2.org/view/packaging/job/packaging_linux/lastSuccessfulBuild/artifact/ws/ros2-package-linux-x86_64.tar.bz2)

## Platform differences:
 I cannot reproduce it on Windows platform.

**Comment by qiuzhong** [comment]
@minggangw , would you please take a look and see if you can reproduce it?

**Comment by minggangw** [comment]
OK

**Comment by qiuzhong** [comment]
This issue is not produced any more with the new `rclnodejs` version 0.3.5 release.
