### ISSUE TITLE
Subscribe op implementation incompatible with rosbridge protocol spec

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#63]
Here is the `publish` operation interface defined in the [spec](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/ROSBRIDGE_PROTOCOL.md#344-subscribe)
```
{ "op": "subscribe",
  (optional) "id": <string>,
  "topic": <string>,
  (optional) "type": <string>,
  (optional) "throttle_rate": <int>,
  (optional) "queue_length": <int>,
  (optional) "fragment_size": <int>,
  (optional) "compression": <string>
}
```

Though the `throttle_rate`, `queue_length` are optional fields, they will impact the subscriber's behavior. The spec requires:

> If queue_length is specified, then messages are placed into the queue before being sent. 
> If a client has multiple subscriptions to the same topic, then messages are sent at the lowest throttle_rate, with the lowest fragmentation size, and highest queue_length. 

In current implementation of rosbridge, this field was never considered for `subscribe` operation.

**Comment by qiuzhong** [comment]
@minggangw , please take a look and let's discuss whether they'll be implemented or just throw them to the incompatibility table in the README.

**Comment by minggangw** [comment]
There is no such a parameter like `throttle_rate` in ROS 2 if I remember it right, I will check this soon.

**Comment by qiuzhong** [comment]
Right. I didn't find the `queue` keyword in rclnodejs qos policy either.

**Comment by minggangw** [comment]
The parameters which do not exist in ROS 2 will not affect the functionalities of the `ros2-web-brige` and those ones will be ignored. So I think we can close this issue now.

**Comment by qiuzhong** [comment]
So this will not be fixed?

**Comment by minggangw** [comment]
Yes, because the current protocol is designed for ROS1 and we can not redefine it. Maybe we can have an update version in the future.
