### ISSUE TITLE
Failed to run subscribe test cases serially

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#67]
This issue is created for track the failure of CI checking of PR #66. The issue is described as:

* They're subscribe-operation-related.
* Running individual test case will pass
* Failed to run multiple test cases or run it twice
* The failure because of bridge server crash during running the test cases.

This issue may be duplicated to #58.

**Comment by minggangw** [comment]
rclnodejs [v0.3.5](https://www.npmjs.com/package/rclnodejs) has been published on npmjs, please verify this issue again, thanks!

**Comment by qiuzhong** [comment]
As PR #66 can pass now, this issue is fixed.
