### ISSUE TITLE
Bridge server cannot be shutdown by CTRL + C at some condition

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#70]
Fork from #69 , at some condition, especially sending some requests to the bridge server. Then the bridge server cannot be shutdown by `CTRL + C`. You have to send `SIGTERM` signal to kill the bridge server.

![screenshot from 2018-03-14 16-54-38](https://user-images.githubusercontent.com/11829497/37392107-2d9af312-27a8-11e8-8b45-ed5bf53f8506.png)

In he screenshot above, sending `CTRL + C` several times cannot shutdown the bridge server.

**Comment by minggangw** [comment]
I will try to reproduce it and investigate, thanks!

**Comment by minggangw** [comment]
rclnodejs [v0.3.5](https://www.npmjs.com/package/rclnodejs) has been published on npmjs, please verify this issue again, thanks!

**Comment by qiuzhong** [comment]
This issue is not reproduced with the new release so far. Let's close it.
