### ISSUE TITLE
Both ros1 and ros2 message or interface types support

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#72]
This proposal comes from the bridge client to interact with the `rclnodejs`.

In ROS1, like `roslibjs` the message or interface type is defined as `std_msgs/String`, `example_interfaces/AddTwoInts`.

In ROS2, like `rclnodejs`, the message or interface types is defined as `std_msgs/msg/String`, `example_interfaces/srv/AddTwoInts`.

Currently, the bridge server will assume all the message or interface types are in ROS1 format and insert `msg` or `srv`. When the service  is in `rclnodejs` environment, there might be inconsistent code.

Suggest to support both ROS1 and ROS2 message or interface types.

**Comment by minggangw** [comment]
Do you mean the `ros2-web-bridge` can accept the type `example_interfaces/srv/AddTwoInts` and `example_interfaces/AddTwoInts` simultaneously?

**Comment by qiuzhong** [comment]
Yes. This is more convenient.

**Comment by minggangw** [comment]
Good idea, I will implement it.
