### ISSUE TITLE
Rclnodejs dependency crashed when destroying bridge client

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/ros2-web-bridge#86]
The bridge crashed when a web socket client is destroyed. Deeply, the `rclnodejs` crashed during destroying this client. We believe that some tricky issues are caused by this crash: #58, #67, #69.

**Comment by qiuzhong** [comment]
@minggangw , please take a look.

**Comment by minggangw** [comment]
I will take this issue, thanks!

**Comment by minggangw** [comment]
rclnodejs [v0.3.5](https://www.npmjs.com/package/rclnodejs) has been published on npmjs, please verify this issue again, thanks!

**Comment by qiuzhong** [comment]
Sure! I'll run the CI with new release of `rclndoejs` and clarify this bug.

**Comment by qiuzhong** [comment]
With the new release, this issue is not reproduced.
